# Generated by Django 4.1.7 on 2023-03-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullurl', models.CharField(max_length=500)),
                ('newurl', models.CharField(max_length=500)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
